version: '3'

services:
  app:
    tty: true
    build:
      context: './docker'
    ports:
      - 3000:8000
    volumes:
      - ./:/var/www/html
    depends_on:
      - mysql
    networks:
      - commodities
  mysql:
    image: 'mysql:8'
    environment:
      MYSQL_DATABASE: commodities
      MYSQL_ROOT_PASSWORD: password
    ports:
     - "3306:3306"
    volumes:
      - ./db-data:/var/lib/mysql
    networks:
      - commodities
  redis:
    image: 'redis:latest'
    ports:
      - "6379:6379"
    volumes:
      - ./cache:/data
    networks:
      - commodities
networks:
  commodities: